server:
  port: 9191
  

spring:  application:    name: API-GATEWAY  cloud:    gateway:      routes:      - id: CAR
        uri: lb://CAR
        predicates:        - Path=/cars/**      - id: USER
        uri: lb://USER
        predicates:        - Path=/users/**              

eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka/  instance:    hostname: localhost